keys:
  - &yubi-master1 age1yubikey1qd84d0gr6gw0kdjztwkgk8h2k5f5477c2eng5j3d9c5qavmeylwx29fcsa5
  - &yubi-master2 age1yubikey1qvkcdmncywzgx4vvhmel4zv8cx3zzgmyx2rzvn9w6u8d95k3qatzqcrm7kj
  - &yubi-master3 age1yubikey1qdpmtxksz55pzfaju625atdyhtksvsclmxhuqqux6s352wq43ge0cg0cw26
  - &console age12e0zcqpclf8gh0wu39alq3ux9u0rpu5tc4qtlqvpldkd79ew0p2smnklp0
  - &srv-n1 age1rq9r6xg57v9v07usktvug8rqv4cvp57qq5gr0yfw23ugxu88rprq75jr9m
  - &srv-n2 age1dtahzr3uqenkj4gt6p8ranheglmh9nhl9tasyjj8ezm9xzqpx9dqtvaups
  - &srv-n3 age18apjd378vwlnts64wznwh9lknndacxakjdwl0ldstplzkpwspf7qw77w3p
  - &pangolin age1n7luzkfg2t0a44uqsz97f2gvjhk3fys908skpd8uzkg98ah3fyashcc5ms
  - &jellyfin age14z74sl0u6el5krjlp335zeg8uaeerlnt9yhxlu6zrjt723m24peqh4r9jc
  - &runner age1aw5yu9dwdv97d0kpwlt949wq0u7t5q3mk3alrvg02rp60w5whu2sz80pgx
  - &mongoose age18sldhysg5dyzm6fr6c00ef5nsyh5np5rm5tf88lupd5z66zeeppqy8yutj
  - &aliased age1r8cgqhrlu8xkywddf3663yuuuml5rdfsgrhsa7hgkzsfk5ejvyjqxsykdd
  - &wazuh age1rfpjxx3g876g8k0kvlntgnc5lttk52whvfga8sfxh6zcf7p8w9nqyxvtk0
  - &filebrowser age100lvh3gnafupwdwtdnwn2fllfe8lfxxtye8hhd9dcfl0kdnw2fhsqsdssg

creation_rules:
  # sops matches top to bottom, secrets always start with "host."
  # so regex should be pretty stable
  - path_regex: secrets/console\.
    key_groups:
      - age: [*yubi-master1, *yubi-master2, *yubi-master3, *console]
  - path_regex: secrets/srv-n1\.
    key_groups:
      - age: [*yubi-master1, *yubi-master2, *yubi-master3, *srv-n1]
  - path_regex: secrets/srv-n2\.
    key_groups:
      - age: [*yubi-master1, *yubi-master2, *yubi-master3, *srv-n2]
  - path_regex: secrets/srv-n3\.
    key_groups:
      - age: [*yubi-master1, *yubi-master2, *yubi-master3, *srv-n3]
  - path_regex: secrets/pangolin\.
    key_groups:
      - age: [*yubi-master1, *yubi-master2, *yubi-master3, *pangolin]
  - path_regex: secrets/jellyfin\.
    key_groups:
      - age: [*yubi-master1, *yubi-master2, *yubi-master3, *jellyfin]
  - path_regex: secrets/runner\.
    key_groups:
      - age: [*yubi-master1, *yubi-master2, *yubi-master3, *runner]
  - path_regex: secrets/mongoose\.
    key_groups:
      - age: [*yubi-master1, *yubi-master2, *yubi-master3, *mongoose]
  - path_regex: secrets/aliased\.
    key_groups:
      - age: [*yubi-master1, *yubi-master2, *yubi-master3, *aliased]
  - path_regex: secrets/wazuh\.
    key_groups:
      - age: [*yubi-master1, *yubi-master2, *yubi-master3, *wazuh]
  - path_regex: secrets/filebrowser\.
    key_groups:
      - age: [*yubi-master1, *yubi-master2, *yubi-master3, *filebrowser]

  - path_regex: secrets/.*
    key_groups:
      - age: [*yubi-master1, *yubi-master2, *yubi-master3]
